parameters:
#    bootcamp_layout.example.class: Bootcamp\LayoutBundle\Example

services:
#    bootcamp_layout.example:
#        class: %bootcamp_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
