bootcamp_admin:
    resource: "@BootcampAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

bootcamp_panel:
    resource: "@BootcampPanelBundle/Resources/config/routing.yml"
    prefix:   /panel

bootcamp_jobeet:
    resource: "@BootcampJobeetBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /easyadmin

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
facebook_login:
    pattern: /login/check-facebook