bootcamp_user:
    resource: "@BootcampUserBundle/Resources/config/routing.yml"
    prefix:   /

BootcampAdminBundle_admin_bootcamp_admin_bundle_Bootcamp:
    resource: "@BootcampAdminBundle/Controller/Bootcamp/"
    type:     admingenerator
    prefix:   /admin/bootcamp_admin_bundle/Bootcamp

bootcamp_admin:
    resource: "@BootcampAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

bootcamp_panel:
    resource: "@BootcampPanelBundle/Resources/config/routing.yml"
    prefix:   /panel

bootcamp_jobeet:
    resource: "@BootcampJobeetBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

