parameters:
#    bootcamp_user.example.class: Bootcamp\UserBundle\Example

services:
#    bootcamp_user.example:
#        class: %bootcamp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
