bootcamp_panel_homepage:
    path:     /
    defaults: { _controller: BootcampPanelBundle:Default:index }
   
bootcamp_panel_list:
    path:     /list
    defaults: { _controller: BootcampPanelBundle:Job:list, page: 1 }
    requirements: { page: \d+ }
   
bootcamp_panel_new:
    path:     /new
    defaults: { _controller: BootcampPanelBundle:Job:new }
    
bootcamp_panel_edit:
    path:     /edit/{id}
    defaults: { _controller: BootcampPanelBundle:Job:edit }
    
bootcamp_panel_delete:
    path:     /delete/{id}
    defaults: { _controller: BootcampPanelBundle:Job:delete }
    
bootcamp_panel_details:
    path:     /details/{id}
    defaults: { _controller: BootcampPanelBundle:Job:details }