parameters:
#    bootcamp_jobeet.example.class: Bootcamp\JobeetBundle\Example

services:
#    bootcamp_jobeet.example:
#        class: %bootcamp_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bootcamp_user.registration.form.type:
        class: Bootcamp\JobeetBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: bootcamp_user_registration }
