parameters:
#    bootcamp_jobeet.example.class: Bootcamp\JobeetBundle\Example

services:
    
    my_user_provider:
        class: Bootcamp\JobeetBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]

    bootcamp_user.registration.form.type:
        class: Bootcamp\JobeetBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: bootcamp_user_registration }
