parameters:
#    bootcamp_jobeet.example.class: Bootcamp\JobeetBundle\Example

services:
#    bootcamp_jobeet.example:
#        class: %bootcamp_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
